#ifndef EventDefine_H
#define EventDefine_H

enum emEventID
{
	IEVENTID_INIT = 1,
	OEVENTID_INIT_RSP,
	IEVENTID_START,
	OEVENTID_START_RSP,
	IEVENTID_USERLOGIN_RSP,
	IEVENTID_USERINITIALIZED_RSP,

	IEVENTID_RTNTRADE,

	OEVENTID_REGISTERAPI_REQ,
	OEVENTID_REGISTERSPI_REQ,
	OEVENTID_USERLOGIN_REQ,
};


#endif // EventDefine_H
